<a href="https://colab.research.google.com/github/JaviLaura/Cleaning_Building_Permits_Data/blob/main/Building_Permits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<img src="https://static.junilearning.com/images/juni_logo.png" height=75 align=center hspace="5px"> **DS7 Project 1: Building Permits**
<img src="https://static.junilearning.com/python_data_science/trolley.jpeg" height=200>

"A <b>building permit</b> is an official approval document issued by a governmental agency that allows you or your contractor to proceed with a construction or remodeling project on one's property." 

You've been given over 200 thousand records containing information about building permits in San Francisco between 2013 and 2018. Unfortunately, some of the data is missing! Let's clean up this dataset!

https://static.junilearning.com/python_data_science/building_permits.csv

<h3>Get to Know Your Data:</h3>

Create a DataFrame and display a sample of 3 rows.<br>

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

buildDF = pd.read_csv("https://static.junilearning.com/python_data_science/building_permits.csv")
display(buildDF)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

Next, display the data types of each column.

In [ ]:
buildDF.isnull().sum()

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

In [ ]:
buildDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 43 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Permit Number                           198900 non-null  object
 1   Permit Type                             198900 non-null  int64
 2   Permit Type Definition                  198900 non-null  object
 3   Permit Creation Date                    198900 non-null  object
 4   Block                                   198900 non-null  object
 5   Lot                                     198900 non-null  object
 6   Street Number                           198900 non-null  int64
 7   Street Number Suffix                    2216 non-null    object
 8   Street Name                             198900 non-null  object
 9   Street Suffix                           196132 non-null  object
 10  Unit                                    29479 non-null   float64
 11  Unit Suffix                             1961 non-null    object
 12  Description                             198610 non-null  object
 13  Current Status                          198900 non-null  object
 14  Current Status Date                     198900 non-null  object
 15  Filed Date                              198900 non-null  object
 16  Issued Date                             183960 non-null  object
 17  Completed Date                          97191 non-null   object
 18  First Construction Document Date        183954 non-null  object
 19  Structural Notification                 6922 non-null    object
 20  Number of Existing Stories              156116 non-null  float64
 21  Number of Proposed Stories              156032 non-null  float64
 22  Voluntary Soft-Story Retrofit           35 non-null      object
 23  Fire Only Permit                        18827 non-null   object
 24  Permit Expiration Date                  147020 non-null  object
 25  Estimated Cost                          160834 non-null  float64
 26  Revised Cost                            192834 non-null  float64
 27  Existing Use                            157786 non-null  object
 28  Existing Units                          147362 non-null  float64
 29  Proposed Use                            156461 non-null  object
 30  Proposed Units                          147989 non-null  float64
 31  Plansets                                161591 non-null  float64
 32  TIDF Compliance                         2 non-null       object
 33  Existing Construction Type              155534 non-null  float64
 34  Existing Construction Type Description  155534 non-null  object
 35  Proposed Construction Type              155738 non-null  float64
 36  Proposed Construction Type Description  155738 non-null  object
 37  Site Permit                             5359 non-null    object
 38  Supervisor District                     197183 non-null  float64
 39  Neighborhoods - Analysis Boundaries     197175 non-null  object
 40  Zipcode                                 197184 non-null  float64
 41  Location                                197200 non-null  object
 42  Record ID                               198900 non-null  int64
dtypes: float64(12), int64(3), object(28)
memory usage: 65.3+ MB

Now display the number of null or N/A values.

In [ ]:
display(buildDF[buildDF["Street Number Suffix"].notna()])

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
92,201408254591,8,otc alterations permit,08/25/2014,3509,029,63,A,Grace,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,6.0,South of Market,94103.0,"(37.774944547030586, -122.41443674356925)",1353299454075
146,M803987,8,otc alterations permit,07/03/2017,0821,073,843,C,Hayes,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94117.0,"(37.775671880692904, -122.43022136710104)",1469150425694
164,201707141931,2,new construction wood frame,07/14/2017,1193,048,2150,A,Hayes,St,...,NaN,NaN,5.0,wood frame (5),Y,5.0,Lone Mountain/USF,94117.0,"(37.77347316353236, -122.45200535060522)",147059391960
200,M816647,8,otc alterations permit,08/04/2017,0821,073,843,C,Hayes,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94117.0,"(37.775671880692904, -122.43022136710104)",1473476425694
273,M829468,8,otc alterations permit,09/08/2017,3702,390,33,A,08th,St,...,NaN,NaN,NaN,NaN,NaN,6.0,South of Market,94103.0,"(37.77850219390184, -122.413426065671)",1478111509834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198762,201802232089,8,otc alterations permit,02/23/2018,0542,038,1977,B,Union,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.79734416546348, -122.43163903779495)",1498216359379
198771,201802232097,8,otc alterations permit,02/23/2018,3117,049A,425,A,Monterey,Bl,...,5.0,wood frame (5),5.0,wood frame (5),NaN,7.0,West of Twin Peaks,94112.0,"(37.73135521046475, -122.44488173732859)",1498225390708
198772,201802232097,8,otc alterations permit,02/23/2018,3117,049A,425,B,Monterey,Bl,...,5.0,wood frame (5),5.0,wood frame (5),NaN,7.0,West of Twin Peaks,94112.0,"(37.73135521046475, -122.44488173732859)",1498226390709
198803,201802232123,8,otc alterations permit,02/23/2018,6655,080,305,A,30th,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Glen Park,94131.0,"(37.741798811634375, -122.42712285786553)",1498258493911
198851,201504153737,3,additions alterations or repairs,04/15/2015,6685,049,240,A,Chenery,St,...,5.0,wood frame (5),5.0,wood frame (5),Y,8.0,Glen Park,94131.0,"(37.73832420066468, -122.42656228166192)",1498307510751

In [ ]:
display(buildDF[buildDF["Zipcode"].notna()])

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198881,M893407,8,otc alterations permit,02/23/2018,0018,004,2300,NaN,Stockton,St,...,NaN,NaN,NaN,NaN,NaN,3.0,North Beach,94133.0,"(37.80747140583783, -122.41024025753224)",1498338347099
198882,201802232172,8,otc alterations permit,02/23/2018,6021,001B,730,NaN,Excelsior,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Excelsior,94112.0,"(37.723206757170836, -122.42763728105176)",1498339194341
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,NaN,Geary,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78696971667916, -122.40936701144197)",149834069380
198884,M893447,8,otc alterations permit,02/23/2018,3504,030,1699,NaN,Market,St,...,NaN,NaN,NaN,NaN,NaN,6.0,Mission,94103.0,"(37.77217130976155, -122.42193576313322)",1498341156230
198885,201802232173,8,otc alterations permit,02/23/2018,2150,001A,2007,NaN,30th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94116.0,"(37.74976582284573, -122.48824447038214)",1498342127659

Where are we missing data? Is this a problem?
<br>
Student Analysis:

<h3>Data Intuition</h3>

Data can be missing for one of two reasons:<br>
<ol>
<li>It doesn't exist</li>
<li>It wasn't recorded</li>
</ol>

For example, the "age of the oldest child" doesn't exist in a family that doesn't have any children. However, the "total number of living family members" will always exist, but may not be recorded. We can guess the values of unrecorded data, but it wouldn't make sense to guess for data that doesn't exist.

Take a look at the `Street Number Suffix` column in the DataFrame, is this because these values don't exist or weren't recorded? 
How about `Zipcode`? Once you've come to conclusions about these columns, try thinking through the others. 

Student Analysis:

Would we be able to get accurate insights about the `Fire Only Permit`, how about the `Neighborhoods - Analysis Boundries`. Why?
<br>
Student Analysis:

<h3>Clean the Data</h3>

Let's try cleaning the data in 3 different ways: dropping rows, dropping columns, and filling in data. <br>
Start by dropping all rows that contain a null value. What rows are left?<br>
Then drop all columns that conatin a null value? What columns are left?<br>
Finally, fill in missing values with a 0 by using `fillna(0)`

Student Analysis:

In [ ]:
#Delete rows
buildDFclean_1 = buildDF.dropna()
display(buildDFclean_1)

Empty DataFrame
Columns: [Permit Number, Permit Type, Permit Type Definition, Permit Creation Date, Block, Lot, Street Number, Street Number Suffix, Street Name, Street Suffix, Unit, Unit Suffix, Description, Current Status, Current Status Date, Filed Date, Issued Date, Completed Date, First Construction Document Date, Structural Notification, Number of Existing Stories, Number of Proposed Stories, Voluntary Soft-Story Retrofit, Fire Only Permit, Permit Expiration Date, Estimated Cost, Revised Cost, Existing Use, Existing Units, Proposed Use, Proposed Units, Plansets, TIDF Compliance, Existing Construction Type, Existing Construction Type Description, Proposed Construction Type, Proposed Construction Type Description, Site Permit, Supervisor District, Neighborhoods - Analysis Boundaries, Zipcode, Location, Record ID]
Index: []

[0 rows x 43 columns]

In [ ]:
#Delete columns
buildDFclean_2 = buildDF.dropna(axis=1)
display(buildDFclean_2)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Current Status,Current Status Date,Filed Date,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,expired,12/21/2017,05/06/2015,1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,issued,08/03/2017,04/19/2016,1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,withdrawn,09/26/2017,05/27/2016,1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,complete,07/24/2017,11/07/2016,1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,issued,12/01/2017,11/28/2016,144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,Montgomery,issued,12/05/2017,12/05/2017,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,Bush,issued,12/06/2017,12/05/2017,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,Indiana,issued,12/06/2017,12/06/2017,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,Sutter,issued,12/06/2017,12/06/2017,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,Pacific,issued,12/07/2017,12/07/2017,1489796283803

In [ ]:
#Fill in missing values

buildDFclean_3 = buildDF.fillna(0)
display(buildDFclean_3)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,0,Ellis,St,...,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,0,Geary,St,...,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,0,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,0,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,0,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,0,Market,St,...,3.0,constr type 3,0.0,0,0,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,0,Montgomery,St,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,0,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),0,0.0,0,0.0,0,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,0,Indiana,St,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,0,Sutter,St,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,0,Pacific,Av,...,0.0,0,0.0,0,0,0.0,0,0.0,0,1489796283803

Now try calculating the mean of `Number of Existing Stories` with the original DataFrame, and the one with filled in values. How do they differ? Why? Note that most summarizing statistics ignore null values by default. 
When is it a good idea to fill in null values and when is it not?

Student Analysis:

In [ ]:
buildDFclean_3["Number of Existing Stories"].mean()

4.478443941679235

In [ ]:
buildDF["Number of Existing Stories"].mean()

5.705773271157344

In [ ]:
We should only fill in values that exist, but weren't recorded. Number of existing stories is a value that exists but wasn't recorded. When we fill in the values to 0, it brings down the average. This is probably an unintended result, which is why we should be careful when filling values.